# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adamenn <- function(Y, X, newX, labels, K, K_0, K_1, K_2, L, c, n_iterations) {
    .Call('_DistanceLearning_adamenn', PACKAGE = 'DistanceLearning', Y, X, newX, labels, K, K_0, K_1, K_2, L, c, n_iterations)
}

dann <- function(Y, X, newX, K, K_M, epsilon, n_iterations) {
    .Call('_DistanceLearning_dann', PACKAGE = 'DistanceLearning', Y, X, newX, K, K_M, epsilon, n_iterations)
}

dca <- function(X, chunklets, unique_chunklets, D, total_dims) {
    .Call('_DistanceLearning_dca', PACKAGE = 'DistanceLearning', X, chunklets, unique_chunklets, D, total_dims)
}

getX_D_neg_1_2 <- function(Y, X, sorted_unique_labels, simlist, difflist) {
    .Call('_DistanceLearning_getX_D_neg_1_2', PACKAGE = 'DistanceLearning', Y, X, sorted_unique_labels, simlist, difflist)
}

Approximate_X_D_neg_1_2 <- function(Y, X) {
    .Call('_DistanceLearning_Approximate_X_D_neg_1_2', PACKAGE = 'DistanceLearning', Y, X)
}

Approximate_X_tilde_S <- function(Y, X, X_D_neg_1_2) {
    .Call('_DistanceLearning_Approximate_X_tilde_S', PACKAGE = 'DistanceLearning', Y, X, X_D_neg_1_2)
}

getS_1_2 <- function(Y, X, X_D_neg_1_2, sorted_unique_labels, simlist) {
    .Call('_DistanceLearning_getS_1_2', PACKAGE = 'DistanceLearning', Y, X, X_D_neg_1_2, sorted_unique_labels, simlist)
}

fenn <- function(Y, X, sorted_unique_labels) {
    .Call('_DistanceLearning_fenn', PACKAGE = 'DistanceLearning', Y, X, sorted_unique_labels)
}

lfda <- function(Y, X, labels, total_dims, method) {
    .Call('_DistanceLearning_lfda', PACKAGE = 'DistanceLearning', Y, X, labels, total_dims, method)
}

nca <- function(Y, X, labels, iterations, learning_rate) {
    .Call('_DistanceLearning_nca', PACKAGE = 'DistanceLearning', Y, X, labels, iterations, learning_rate)
}

rca <- function(X, chunklets, unique_chunklets, total_dims) {
    .Call('_DistanceLearning_rca', PACKAGE = 'DistanceLearning', X, chunklets, unique_chunklets, total_dims)
}

sumOuterProducts <- function(X, S, n_cols) {
    .Call('_DistanceLearning_sumOuterProducts', PACKAGE = 'DistanceLearning', X, S, n_cols)
}

getD <- function(Y, X, labels) {
    .Call('_DistanceLearning_getD', PACKAGE = 'DistanceLearning', Y, X, labels)
}

getX_S <- function(Y, X, labels) {
    .Call('_DistanceLearning_getX_S', PACKAGE = 'DistanceLearning', Y, X, labels)
}

xing <- function(Y, X, labels, X_S, D, weight_matrix, learning_rate, error, epsilon, max_iterations) {
    .Call('_DistanceLearning_xing', PACKAGE = 'DistanceLearning', Y, X, labels, X_S, D, weight_matrix, learning_rate, error, epsilon, max_iterations)
}

